### ISSUE TITLE
Convert tags to dropdown list

### ISSUE THREAD

**Issue by Ravina-Deogadkar** [Ravina-Deogadkar/snippet-library#12]
Convert tags on the new snippet modal to drop down.

![image](https://github.com/Ravina-Deogadkar/snippet-library/assets/49125074/713ca314-dd6d-4cf2-8e62-4215144a72fd)

**Comment by abdejohan** [comment]
Would love to do this if you could assign me this issue. ✌🏽

**Comment by Ravina-Deogadkar** [comment]
Sure go ahead!
