### ISSUE TITLE
Add create new snippet editor modal

### ISSUE THREAD

**Issue by Ravina-Deogadkar** [Ravina-Deogadkar/snippet-library#5]
Add snippet editor popup modal that will have following fields

- Title (Textbox)
- Code snippet (Text Editor)
- Tags (eg: C#, Java)
- StarCount (default 0)
- CreationDate 
-  ModifiedDate

**Comment by Shrenik0321** [comment]
Hey @Ravina-Deogadkar , i would like to work on this issue. Can you assign me?
Also, it would be appreciated if you could elaborate on the issue.

**Comment by Ravina-Deogadkar** [comment]
Hey @Shrenik0321 go ahead. I'll assign this to you.

I am thinking of having something like this
![image](https://github.com/Ravina-Deogadkar/snippet-library/assets/49125074/f8bcb419-826c-4cf3-bae3-a65582374965)

you have to add a create new snippet card on dashboard page and on clicking on card it will open up a modal with editor which will look like this.

![image](https://github.com/Ravina-Deogadkar/snippet-library/assets/49125074/1a43a25d-2a62-4c55-bcaf-e34ed52da84d)

Fork this repo and start working!..

**Comment by Ravina-Deogadkar** [comment]
For code editor you can check https://github.com/microsoft/monaco-editor

**Comment by Zayan-dev** [comment]
Hello, I am new to open source, could you guide me how do you want to resolve this issue, do you want a HTML, CSS and JS folder?

**Comment by Shrenik0321** [comment]
Awesome! I'll get to work @Ravina-Deogadkar

**Comment by Ravina-Deogadkar** [comment]
> Hello, I am new to open source, could you guide me how do you want to resolve this issue, do you want a HTML, CSS and JS folder?

Hi @Zayan-dev , this issue is already assigned you can look for some other issues.

**Comment by Ravina-Deogadkar** [comment]
#9 PR is merged
